services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq  
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
      
volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local      